### ISSUE TITLE
Create windows install script

### ISSUE THREAD

**Issue by dkomeza** [dkomeza/tiny-git-helper#37]
# Create an install script for windows.
It should be based on the linux install script and take inspiration from the Bun.sh powershell install script.

## Tasks
- [ ] - User friendly installation. (possibly run tgh after installing to set the tgh config)
- [ ] - Make sure to download the latest version from the github releases
- [ ] - Compatibility with Windows 10 and Windows 11
- [ ] - Add tgh to PATH
- [ ] - Create a test script for CI/CD
