### ISSUE TITLE
Update the linux/macos install script

### ISSUE THREAD

**Issue by dkomeza** [dkomeza/tiny-git-helper#38]
# Update the unix installation script

The current script is extremely simple and basic, and needs more robust checks.

## ToDo list:
- [x] - Update the way the script fetches user data
- [x] - Minimise the use of external requirements (e.x. sed)
- [x] - Change the way the PATH is handled
- [x] - Add better looking text and visuals
- [x] - Install tgh without sudo privileges
